default_language_version:
    python: python3.8

exclude:
    setup.py
repos:
    # Format code
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
            args: ["--line-length=120"]

    # Sort imports
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ["--profile", "black"]

    # Run pre-commit-hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: detect-private-key
          - id: mixed-line-ending

    # Run black on python code in .md files
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
          - id: blacken-docs

    # Delete unused variables and imports
    - repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
          - id: autoflake
            args: ["--in-place", "--recursive", "--remove-unused-variables"]

    # Show warnings for code standards not respected
    - repo: https://github.com/pycqa/pylint
      rev: v2.14.5
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            language: python
            types: [python]
            args: ["--max-line-length=120",
                   "--min-similarity-lines=10",
                   "--max-attributes=30",
                   "--max-locals=40",
                   "--max-branches=15",
                   "--max-statements=60",
                   "--max-nested-blocks=10",
                   "--disable=E0401,E1120,R0903,R0913,E1102",
                   "--fail-under=8",
                   "--ignore-paths=configs,dab_occupancy_trainer/data_preprocessing,unit_tests,setup.py,version.py,dab_occupancy_trainer/utils/bbox_utils.py"]
            verbose: true

    # Show warnings for code standards not respected
    - repo: https://github.com/pycqa/flake8
      rev: 5.0.4
      hooks:
          - id: flake8
            args: ["--max-line-length=120", "--ignore=F403,F405,E203,W503"]

    # Transform git commit messages into Jira smart commits
    - repo: https://github.com/avilaton/add-msg-issue-prefix-hook
      rev: v0.0.5
      hooks:
          - id: add-msg-issue-prefix

default_stages:
  - commit
